# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Matteo Mancanelli"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Matteo Mancanelli"
description              : "Personal website of a computer scientist and logic enthusiast"
url                      : "https://www.matteomancanelli.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/" # the subpath of your site, e.g. "/blog"
repository               : "mancanelli/mancanelli.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : "Home Page" # overrides the website title displayed in the masthead, use " " for no title
#breadcrumbs             : # true, false (default)
words_per_minute         : 200

# TODO
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"

reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)

after_footer_scripts:
  - /assets/js/custom.js

search                   : false
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : true
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true

# SEO Related
google_site_verification : google24834cf79a491fea.html
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing TODO
twitter:
  username               : m_mancanelli
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles

social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/m_mancanelli"
    - "https://www.facebook.com/matteo.mancanelli"
    - "https://www.linkedin.com/in/matteo-mancanelli/"
    - "https://github.com/matteomancanelli"

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-N79D13Z2C5"
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Matteo Mancanelli"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "PhD candidate in the Italian National PhD<br/>in AI at Sapienza University of Rome"
  location         : 
  email            : 
  links:
    - label: "Email"
      icon: "far fa-fw fa-envelope"
      url: "mailto:mancanelli@diag.uniroma1.it"
    - label: "ORCID"
      icon: "ai ai-fw ai-orcid"
      url: "https://orcid.org/0009-0004-9547-7115"
    - label: "Google Scholar"
      icon: "ai ai-fw ai-google-scholar-square"
      url: "https://scholar.google.com/citations?user=atdTiGoAAAAJ"
#    - label: "Semantic Scholar"
#      icon: "ai ai-fw ai-semantic-scholar"
#      url: "https://www.semanticscholar.org/author/Matteo-Mancanelli/2257037884"
    - label: "DBLP"
      icon: "ai ai-fw ai-dblp"
      url: "https://dblp.org/pid/358/9184.html"
#    - label: "Scopus"
#      icon: "ai ai-fw ai-scopus"
#      url: "https://www.scopus.com/authid/detail.uri?authorId=58666548700"
#    - label: "ResearchGate"
#      icon: "fab fa-fw fa-researchgate"
#      url: "https://www.researchgate.net/profile/Matteo-Mancanelli"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mancanelli"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/matteo-mancanelli/"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter"
#      url: "https://twitter.com/m_mancanelli"

# TODO
#    - label: "Feed"
#      icon: "fas fa-fw fa-rss-square"
#      url: "https://mancanelli.github.io/feed.xml"
#    - label: "Facebook"
#      icon: "fab fa-fw fa-facebook"
#      url: "https://www.facebook.com/matteo.mancanelli/"


# Site Footer
footer:
  links:
    - label: "Email"
      icon: "far fa-fw fa-envelope"
      url: "mailto:mancanelli@diag.uniroma1.it"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/m_mancanelli"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/matteo.mancanelli/"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mancanelli"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/matteo-mancanelli/"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title
timezone: Europe/Rome
#paginate: 5
#paginate_path: /page:num/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag


relative_links:
  enabled:     true
  collections: true

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: custom-single
      toc: true
      toc_sticky: true
      author_profile: true
      show_date: true
      read_time: true
      comments: # true
      share: true
      related: true
      lang: en
  - scope:
      path: ""
      type: pages
    values:
      layout: custom-single
      author_profile: true
      lang: en

lang: en

collections: 
  publications:
    output: false
    permalink: /:collection/:title
  teaching:
    output: false
    permalink: /:collection/:title
  talks:
    output: false
    permalink: /:collection/:title
  acks:
    output: false
    permalink: /:collection/:title
  reviews:
    output: false
    permalink: /:collection/:title